language: python
services:
  - postgresql
python:
  - "3.5"
install:
  - "pip install -r requirements/test.txt"
script:
  - pytest
  - pytest --cov=consumer tests/
after_success:
  - coveralls

notifications:
  email: false

# This reportedly works around an issue downloading packages from pypi on
# travis. Consider removing this after the underlying issue is fixed.
# https://github.com/travis-ci/travis-ci/issues/2389
sudo: false

matrix:
  fast_finish: true

cache: pip
